name: Keep App Alive

on:
  workflow_dispatch:  # Handmatige trigger
  schedule:
    - cron: "*/15 * * * *"  # Automatische trigger elke 15 minuten

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Keep Render and Railway Apps Alive
        run: |
          echo "Pinging Render App..."
          curl -s -o /dev/null https://volvo-tools.onrender.com/
          echo "Pinging PSF Dashboard..."
          curl -s -o /dev/null https://psf-dashboard.onrender.com/
