name: Keep App Alive

on:
  workflow_dispatch: # Handmatige trigger
  schedule:
    - cron: "*/13 * * * *" # Automatische trigger elke 15 minuten

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Send ping to Render App
        run: |
          curl -s -o /dev/null https://bomconverter.onrender.com/home
